---
stages:
  - test
  - release
  - build
  - publish

.go_template_defaults:
  stage: test
.semver_template_defaults:
  stage: release
variables:
  SEMVER_PREFIX: v
include:
  - remote: https://gitlab.com/bonsai-oss/organization/ci-templates/-/raw/main/templates/language/go.yml
  - remote: https://gitlab.com/bonsai-oss/organization/ci-templates/-/raw/main/templates/release/semver.yml

debian packagebuild:
  stage: build
  image: registry.fsrv.services/fsrvcorp/container/debian-build:latest@sha256:56cab119c9d111c6f18ad0bbccacd3e36c9a6067431674246c593f3a2d5e43a8
  variables:
    CGO_ENABLED: 0
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/
  parallel:
    matrix:
      - GOOS: linux
        GOARCH: [amd64, arm64]
  before_script:
    - apt update && apt install -y binutils-aarch64-linux-gnu
    - go build -o nyx -ldflags="-s -w" -trimpath ./cmd/nyx
  script:
    - export VERSION="$(echo $CI_COMMIT_TAG | sed 's/^v//')"
    - sed -i "s/%VERSION%/$VERSION/g" debian/changelog
    - sed -i "s/%ARCHITECTURE%/$GOARCH/g" debian/control
    - mkdir package && mv debian package
    - (cd package && dpkg-buildpackage -rfakeroot -b -uc -us --host-arch $GOARCH)
  artifacts:
    paths:
      - "*.deb"

packagecloud upload:
    stage: publish
    dependencies:
      - debian packagebuild
    needs:
      - debian packagebuild
    image: ruby@sha256:7e50b37e901cebfb045a5b7d9fb30dd3cfeb03d8ad575839849246053e2c97b7
    rules:
      - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/
    parallel:
      matrix:
        - DISTRO: [debian]
          VERSION: [buster, bullseye]
    before_script:
      - gem install package_cloud
    script:
      - package_cloud push fsrv/production/$DISTRO/$VERSION nyx_*.deb