---
stages:
  - test
  - update
  - release
  - publish

lint:
  image: registry.gitlab.com/gitlab-org/gitlab-build-images:golangci-lint-alpine
  stage: test
  script:
    - golangci-lint run ./... --issues-exit-code 0 --out-format code-climate | tee gl-code-quality-report.json | jq -r '.[] | "\(.location.path):\(.location.lines.begin) \(.description)"'
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
    paths:
      - gl-code-quality-report.json

go_fmt:
  image: golang
  stage: test
  script:
    - go fmt ./...

go_test:
  image: golang
  stage: test
  before_script:
    - go install gotest.tools/gotestsum@latest
  script:
    - go fmt ./...
    - go test -v ./...
    - /go/bin/gotestsum --junitfile report.xml --format testname
  artifacts:
    when: always
    reports:
      junit: report.xml

semantic_release:
  image: registry.fsrv.services/fsrvcorp/container/payipi:latest
  stage: release
  variables:
    GIT_STRATEGY: clone
    GIT_DEPTH: 0
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - get-next-version -f json
    - VERSION="$(get-next-version -f json | jq -r 'select(.hasNextVersion==true) | .version')"
    - echo $VERSION
    - test -z "$VERSION" || curl --silent --request POST --header "PRIVATE-TOKEN:${CI_BOT_TOKEN}" "https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/repository/tags?tag_name=v${VERSION}&ref=${CI_DEFAULT_BRANCH}" | jq

trigger dimp:
  stage: update
  trigger: fsrvcorp/misc/dimp
  variables:
    DIMP_PROJECT_ID: $CI_PROJECT_ID
  only:
    - schedules

debian packagebuild:
  stage: release
  image: registry.fsrv.services/fsrvcorp/container/debian-build:latest
  variables:
    CGO_ENABLED: 0
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/
  parallel:
    matrix:
      - GOOS: linux
        GOARCH: [amd64, arm64]
  before_script:
    - apt update && apt install -y binutils-aarch64-linux-gnu
    - go build -o nyx -ldflags="-s -w" -trimpath ./cmd/nyx
  script:
    - export VERSION="$(echo $CI_COMMIT_TAG | sed 's/^v//')"
    - sed -i "s/%VERSION%/$VERSION/g" debian/changelog
    - sed -i "s/%ARCHITECTURE%/$GOARCH/g" debian/control
    - mkdir package && mv debian package
    - (cd package && dpkg-buildpackage -rfakeroot -b -uc -us --host-arch $GOARCH)
  artifacts:
    paths:
      - "*.deb"

packagecloud upload:
    stage: publish
    dependencies:
      - debian packagebuild
    needs:
      - debian packagebuild
    image: ruby
    rules:
      - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/
    parallel:
      matrix:
        - DISTRO: [debian]
          VERSION: [buster, bullseye]
    before_script:
      - gem install package_cloud
    script:
      - package_cloud --config=$PACKAGECLOUD_CONFIG push fsrv/testing/$DISTRO/$VERSION *.deb