---
stages:
  - test
  - release
  - build
  - publish

.go_template_defaults:
  stage: test
.semver_template_defaults:
  stage: release
variables:
  SEMVER_PREFIX: v
include:
  - remote: https://gitlab.com/bonsai-oss/organization/ci-templates/-/raw/main/templates/language/go.yml
  - remote: https://gitlab.com/bonsai-oss/organization/ci-templates/-/raw/main/templates/release/semver.yml

debian packagebuild:
  stage: build
  image: registry.fsrv.services/fsrvcorp/container/debian-build:latest@sha256:380d59a3866b34256fe982c21816373bb3508aa94443124304a912a05b2e2130
  variables:
    CGO_ENABLED: 0
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/
  parallel:
    matrix:
      - GOOS: linux
        GOARCH: [amd64, arm64]
  before_script:
    - apt update && apt install -y binutils-aarch64-linux-gnu
    - go build -o nyx -ldflags="-s -w" -trimpath ./cmd/nyx
  script:
    - export VERSION="$(echo $CI_COMMIT_TAG | sed 's/^v//')"
    - sed -i "s/%VERSION%/$VERSION/g" debian/changelog
    - sed -i "s/%ARCHITECTURE%/$GOARCH/g" debian/control
    - mkdir package && mv debian package
    - (cd package && dpkg-buildpackage -rfakeroot -b -uc -us --host-arch $GOARCH)
  artifacts:
    paths:
      - "*.deb"

packagecloud upload:
    stage: publish
    dependencies:
      - debian packagebuild
    needs:
      - debian packagebuild
    image: ruby@sha256:5727a4d0cc8d9f2deaa99c0b22bd5bed6b02e8898f701fef4b4e61ebef896ab0
    rules:
      - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/
    parallel:
      matrix:
        - DISTRO: [debian]
          VERSION: [buster, bullseye]
    before_script:
      - gem install package_cloud
    script:
      - package_cloud push fsrv/production/$DISTRO/$VERSION nyx_*.deb