---
stages:
  - test
  - release
  - build
  - publish

.go_template_defaults:
  stage: test
.semver_template_defaults:
  stage: release
variables:
  SEMVER_PREFIX: v
include:
  - remote: https://gitlab.com/bonsai-oss/organization/ci-templates/-/raw/main/templates/language/go.yml
  - remote: https://gitlab.com/bonsai-oss/organization/ci-templates/-/raw/main/templates/release/semver.yml

debian packagebuild:
  stage: build
  image: registry.fsrv.services/fsrvcorp/container/debian-build:latest@sha256:014ff34b1b6a9a8fed8163b714c69d4b8a3dbebe93fb94bedc9cbb5121051559
  variables:
    CGO_ENABLED: 0
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/
  parallel:
    matrix:
      - GOOS: linux
        GOARCH: [amd64, arm64]
  before_script:
    - apt update && apt install -y binutils-aarch64-linux-gnu
    - go build -o nyx -ldflags="-s -w" -trimpath ./cmd/nyx
  script:
    - export VERSION="$(echo $CI_COMMIT_TAG | sed 's/^v//')"
    - sed -i "s/%VERSION%/$VERSION/g" debian/changelog
    - sed -i "s/%ARCHITECTURE%/$GOARCH/g" debian/control
    - mkdir package && mv debian package
    - (cd package && dpkg-buildpackage -rfakeroot -b -uc -us --host-arch $GOARCH)
  artifacts:
    paths:
      - "*.deb"

packagecloud upload:
    stage: publish
    dependencies:
      - debian packagebuild
    needs:
      - debian packagebuild
    image: ruby@sha256:05ca729e257fc550f4228714a5f6c9f377d4dab92c30b2213340ddb7eec0b597
    rules:
      - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/
    parallel:
      matrix:
        - DISTRO: [debian]
          VERSION: [buster, bullseye]
    before_script:
      - gem install package_cloud
    script:
      - package_cloud push fsrv/production/$DISTRO/$VERSION nyx_*.deb